"""Render the v0.27 autonomous trade-ally escort and defense patch."""
from __future__ import annotations


def render_ally_patch() -> str:
    return r'''
<style id="trade-ally-v027-style">
#allyCardV027 .allyGridV027{display:grid;grid-template-columns:repeat(2,minmax(170px,1fr));gap:7px;margin-top:8px}
#allyCardV027 .allyCellV027{border:1px solid var(--line);background:rgba(15,18,24,.58);padding:7px;font-size:9px;line-height:1.45}
#allyCardV027 .allyCellV027 strong{display:block;color:var(--gold);font-size:11px;margin-bottom:2px}
#allyDialogueV027{border-top:1px solid #6f825b;margin-top:8px;padding-top:8px;display:flex;gap:7px;align-items:center;flex-wrap:wrap}
#allyDialogueV027 .allyStatusV027{color:#c8d5bf;font-size:9px;line-height:1.4;flex:1 1 260px}
#allyDialogueV027 button{background:#293529;border:1px solid #8aa36f;color:#e5efdf;padding:6px 9px;font:9px "Courier New",monospace;cursor:pointer}
#allyDialogueV027 button:disabled{opacity:.42;cursor:not-allowed}
#allyHudV027{position:fixed;z-index:999994;left:max(7px,env(safe-area-inset-left));bottom:max(8px,env(safe-area-inset-bottom));max-width:min(360px,72vw);pointer-events:none;font:8px "Courier New",monospace;color:#dce8d3}
#allyHudV027 .allyHudRowV027{margin-top:3px;background:rgba(13,19,16,.88);border:1px solid #6f825b;padding:4px 6px;display:flex;gap:7px;align-items:center}
#allyHudV027 .allyShieldV027{color:#e2ad45}.allyHpTrackV027{width:64px;height:5px;background:#10151a;border:1px solid #3f4c3b}.allyHpFillV027{height:100%;background:#79c56b}
@media(max-width:650px){#allyCardV027 .allyGridV027{grid-template-columns:1fr}#allyHudV027{max-width:88vw;font-size:7px}}
</style>
<div id="allyHudV027" aria-live="polite"></div>
<script id="trade-ally-v027-script">
(function(){
  "use strict";
  var VERSION="0.27",MAX_ESCORTS=2,FOLLOW_DISTANCE=24,TELEPORT_DISTANCE=190,ENGAGE_RANGE=92,ATTACK_RANGE=19;
  var state={stepCount:0,attackCount:0,defeatCount:0,recallCount:0,lastMessage:"",lastTarget:null};
  function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d||0)}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function agentsList(){try{return typeof agents!=="undefined"&&Array.isArray(agents)?agents:[]}catch(e){return []}}
  function enemies(){try{if(typeof scene!=="undefined"&&scene==="dungeon"&&typeof dungeonEnemies!=="undefined"&&Array.isArray(dungeonEnemies))return dungeonEnemies;if(typeof worldEnemies!=="undefined"&&Array.isArray(worldEnemies))return worldEnemies}catch(e){}return []}
  function isAliveEnemy(e){return !!e&&!e.dead&&!e.eliminated&&n(e.hp,e.health==null?1:e.health)>0}
  function eligible(a){return !!a&&!!a.tradeAllyV026&&!a.eliminated}
  function active(){return agentsList().filter(function(a){return eligible(a)&&!!a.escortActiveV027})}
  function allAllies(){return agentsList().filter(eligible)}
  function ensure(a){if(!a)return a;if(!Number.isFinite(Number(a.escortMaxHpV027)))a.escortMaxHpV027=8;if(!Number.isFinite(Number(a.escortHpV027)))a.escortHpV027=a.escortMaxHpV027;if(!Number.isFinite(Number(a.escortAttackCdV027)))a.escortAttackCdV027=0;if(!Number.isFinite(Number(a.escortHurtCdV027)))a.escortHurtCdV027=0;if(!Number.isFinite(Number(a.escortDownTimerV027)))a.escortDownTimerV027=0;if(!a.escortModeV027)a.escortModeV027="follow";return a}
  function label(a){return String(a&&a.name||a&&a.displayName||"Trade ally")}
  function notify(message){state.lastMessage=String(message||"");try{if(typeof toast==="function")toast(state.lastMessage)}catch(e){}updateSettings();renderHud()}
  function invite(a){ensure(a);if(!eligible(a)){notify(label(a)+" has not yet pledged to defend you.");return false}if(a.escortActiveV027)return true;var current=active();if(current.length>=MAX_ESCORTS){notify("Only "+MAX_ESCORTS+" trade allies can escort you at once.");return false}a.escortActiveV027=true;a.escortDownTimerV027=0;a.escortHpV027=Math.max(1,n(a.escortHpV027,a.escortMaxHpV027));a.currentActivity="escorting and defending the player";notify(label(a)+" joins your escort.");try{if(typeof saveGame==="function")saveGame(true)}catch(e){}return true}
  function dismiss(a,silent){if(!a)return false;a.escortActiveV027=false;a.escortTargetV027=null;a.escortModeV027="follow";if(a.tradeAllyV026)a.currentActivity="protecting a profitable friendship and trade route";if(!silent)notify(label(a)+" returns to normal village work.");try{if(typeof saveGame==="function")saveGame(true)}catch(e){}return true}
  function dismissAll(){active().forEach(function(a){dismiss(a,true)});notify("All trade allies have been dismissed from escort duty.")}
  function recall(){var list=active();list.forEach(function(a,index){ensure(a);var angle=(index/list.length)*Math.PI*2-Math.PI/2;a.x=n(player&&player.x,0)+Math.cos(angle)*18;a.y=n(player&&player.y,0)+Math.sin(angle)*18;a.escortDownTimerV027=0;a.escortHpV027=Math.max(1,n(a.escortHpV027,a.escortMaxHpV027));a.escortTargetV027=null});state.recallCount++;notify(list.length?"Active allies recalled to your position.":"No active trade allies to recall.")}
  function nearestEnemy(a){var best=null,bestD=ENGAGE_RANGE;enemies().forEach(function(e){if(!isAliveEnemy(e))return;var d=Math.hypot(n(e.x,0)-n(a.x,0),n(e.y,0)-n(a.y,0));if(d<bestD){best=e;bestD=d}});return best}
  function moveToward(a,tx,ty,dt,speed){var dx=tx-n(a.x,0),dy=ty-n(a.y,0),d=Math.hypot(dx,dy);if(d<.001)return d;var step=Math.min(d,Math.max(0,dt)*speed);a.x=n(a.x,0)+dx/d*step;a.y=n(a.y,0)+dy/d*step;a.face={x:Math.abs(dx)>Math.abs(dy)?Math.sign(dx):0,y:Math.abs(dy)>=Math.abs(dx)?Math.sign(dy):0};a.moving=step>.05;a.moveVX=dx/d*speed;a.moveVY=dy/d*speed;return d}
  function hurtEnemy(e,damage,a){if(!e)return false;var hpKey=Object.prototype.hasOwnProperty.call(e,"hp")?"hp":"health";e[hpKey]=n(e[hpKey],1)-damage;state.attackCount++;try{if(typeof particles!=="undefined"&&Array.isArray(particles))particles.push({scene:typeof scene!=="undefined"?scene:"world",glyph:"slash",x:n(e.x,0)+5,y:n(e.y,0)+5,vx:0,vy:-12,life:.22,color:"#9ed083"});if(typeof playSfx==="function")playSfx("swing")}catch(err){}if(e[hpKey]<=0){e[hpKey]=0;if(typeof defeatEnemy==="function"){try{defeatEnemy(e,"ally")}catch(err){e.dead=true}}else e.dead=true;state.defeatCount++;a.currentActivity="defending the player from danger";return true}return false}
  function stepEscort(a,index,dt){ensure(a);a.escortAttackCdV027=Math.max(0,n(a.escortAttackCdV027,0)-dt);a.escortHurtCdV027=Math.max(0,n(a.escortHurtCdV027,0)-dt);if(a.escortDownTimerV027>0){a.escortDownTimerV027=Math.max(0,a.escortDownTimerV027-dt);a.moving=false;if(a.escortDownTimerV027===0){a.escortHpV027=Math.max(2,Math.ceil(a.escortMaxHpV027*.5));a.x=n(player&&player.x,0)-14-index*9;a.y=n(player&&player.y,0)+14;a.currentActivity="recovering and resuming escort duty"}return}
    if(typeof scene!=="undefined"&&scene!=="world"&&scene!=="dungeon"){a.moving=false;return}
    var px=n(player&&player.x,0),py=n(player&&player.y,0),pd=Math.hypot(n(a.x,0)-px,n(a.y,0)-py);if(pd>TELEPORT_DISTANCE){a.x=px-18-index*12;a.y=py+16+index*5;a.escortTargetV027=null;pd=0}
    var target=nearestEnemy(a);a.escortTargetV027=target||null;state.lastTarget=target||null;
    if(target){var d=moveToward(a,n(target.x,0),n(target.y,0),dt,82);a.currentActivity="defending the player from "+String(target.type||"an enemy");if(d<=ATTACK_RANGE&&a.escortAttackCdV027<=0){hurtEnemy(target,1,a);a.escortAttackCdV027=.62}if(d<=ATTACK_RANGE+2&&isAliveEnemy(target)&&a.escortHurtCdV027<=0){a.escortHpV027=Math.max(0,n(a.escortHpV027,a.escortMaxHpV027)-1);a.escortHurtCdV027=1.15;if(a.escortHpV027<=0){a.escortDownTimerV027=10;a.escortTargetV027=null;a.currentActivity="downed while defending the player"}}return}
    var face=player&&player.face||{x:0,y:1},side=index%2===0?-1:1,rank=Math.floor(index/2)+1,tx=px-n(face.x,0)*(FOLLOW_DISTANCE+rank*7)+n(face.y,0)*side*13,ty=py-n(face.y,0)*(FOLLOW_DISTANCE+rank*7)-n(face.x,0)*side*13;if(pd>FOLLOW_DISTANCE+8)moveToward(a,tx,ty,dt,68);else{a.moving=false;a.moveVX=0;a.moveVY=0}a.currentActivity="escorting and watching the road";
  }
  function step(dt){var list=active();list.forEach(function(a,index){stepEscort(a,index,Math.min(.12,Math.max(0,n(dt,0))))});state.stepCount++;if(state.stepCount%12===0){renderHud();updateSettings()}}
  function renderHud(){var host=document.getElementById("allyHudV027");if(!host)return;host.innerHTML=active().map(function(a){ensure(a);var pct=Math.round(clamp(n(a.escortHpV027,0)/Math.max(1,n(a.escortMaxHpV027,8)),0,1)*100),status=a.escortDownTimerV027>0?"down "+Math.ceil(a.escortDownTimerV027)+"s":a.escortTargetV027?"engaging":"following";return '<div class="allyHudRowV027"><span class="allyShieldV027">◆</span><span>'+label(a)+'</span><span class="allyHpTrackV027"><span class="allyHpFillV027" style="display:block;width:'+pct+'%"></span></span><span>'+status+'</span></div>'}).join("")}
  function installDialogue(a){var panel=document.getElementById("villagerTradeV026");if(!panel||!a)return false;var old=document.getElementById("allyDialogueV027");if(old)old.remove();ensure(a);var box=document.createElement("div");box.id="allyDialogueV027";var status=document.createElement("div");status.className="allyStatusV027";if(!eligible(a))status.textContent="This villager has not yet crossed the protection threshold.";else if(a.escortActiveV027)status.textContent=label(a)+" is actively escorting you.";else status.textContent=label(a)+" has pledged protection and can join your escort.";box.appendChild(status);var button=document.createElement("button");button.type="button";button.textContent=a.escortActiveV027?"Dismiss escort":"Invite to escort";button.disabled=!eligible(a);button.addEventListener("click",function(){if(a.escortActiveV027)dismiss(a);else invite(a);installDialogue(a)});box.appendChild(button);if(a.escortActiveV027){var recallButton=document.createElement("button");recallButton.type="button";recallButton.textContent="Recall here";recallButton.addEventListener("click",recall);box.appendChild(recallButton)}panel.appendChild(box);return true}
  function settingsHtml(){var allies=allAllies(),escorts=active(),down=escorts.filter(function(a){return n(a.escortDownTimerV027,0)>0}).length;return '<h3>Trade Ally Escort <span class="hdArchitectureBadgeV34">v0.27</span></h3><div class="sub">Villagers who become trade allies can now follow the player, engage nearby enemies, become temporarily downed, recover, and persist through saves. Invite them from their dialogue panel.</div><div class="allyGridV027"><div class="allyCellV027"><strong>'+escorts.length+' / '+MAX_ESCORTS+' active escorts</strong>'+allies.length+' eligible trade allies across the world.</div><div class="allyCellV027"><strong>'+state.attackCount+' ally attacks</strong>'+state.defeatCount+' enemy defeats · '+down+' currently downed.</div></div><div class="row" style="margin-top:9px;justify-content:flex-start"><button class="uibtn" id="recallAlliesV027" type="button">Recall active allies</button><button class="uibtn" id="dismissAlliesV027" type="button">Dismiss all escorts</button></div><div class="sub" style="margin-top:6px">'+String(state.lastMessage||"No escort orders issued yet.")+'</div>'}
  function installSettings(){var wrap=document.getElementById("settingsContent");if(!wrap)return false;var card=document.getElementById("allyCardV027");if(!card){card=document.createElement("div");card.id="allyCardV027";card.className="menuCard";wrap.appendChild(card)}card.innerHTML=settingsHtml();var recallButton=card.querySelector("#recallAlliesV027"),dismissButton=card.querySelector("#dismissAlliesV027");if(recallButton)recallButton.addEventListener("click",recall);if(dismissButton)dismissButton.addEventListener("click",dismissAll);return true}
  function updateSettings(){if(document.getElementById("allyCardV027"))installSettings()}
  function installHooks(){
    if(typeof stepAgents==="function"&&!stepAgents.__alliesV027){var oldStep=stepAgents;stepAgents=function(dt){var result=oldStep.apply(this,arguments);step(dt);return result};stepAgents.__alliesV027=true}
    if(typeof openDialogue==="function"&&!openDialogue.__alliesV027){var oldDialogue=openDialogue;openDialogue=function(a){var result=oldDialogue.apply(this,arguments);setTimeout(function(){installDialogue(a)},40);return result};openDialogue.__alliesV027=true}
    if(typeof renderSettings==="function"&&!renderSettings.__alliesV027){var oldSettings=renderSettings;renderSettings=function(){var result=oldSettings.apply(this,arguments);setTimeout(installSettings,0);return result};renderSettings.__alliesV027=true}
    if(typeof drawCombatEffects==="function"&&!drawCombatEffects.__alliesV027){var oldDraw=drawCombatEffects;drawCombatEffects=function(){var result=oldDraw.apply(this,arguments);try{if(typeof ctx!=="undefined"&&typeof camera!=="undefined")active().forEach(function(a){ensure(a);var x=n(a.x,0)-n(camera.x,0),y=n(a.y,0)-n(camera.y,0),pct=clamp(n(a.escortHpV027,0)/Math.max(1,n(a.escortMaxHpV027,8)),0,1);ctx.save();ctx.fillStyle="#e2ad45";ctx.fillRect(x-2,y-8,14,2);ctx.fillStyle="#79c56b";ctx.fillRect(x-2,y-5,14*pct,2);ctx.restore()})}catch(e){}return result};drawCombatEffects.__alliesV027=true}
    if(typeof snapshot==="function"&&!snapshot.__alliesV027){var oldSnapshot=snapshot;snapshot=function(){var data=oldSnapshot.apply(this,arguments);data.version=Math.max(27,n(data.version,0));data.alliesV027=agentsList().filter(function(a){return a.tradeAllyV026||a.escortActiveV027}).map(function(a){ensure(a);return {id:a.id,active:!!a.escortActiveV027,hp:n(a.escortHpV027,a.escortMaxHpV027),max_hp:n(a.escortMaxHpV027,8),down_timer:n(a.escortDownTimerV027,0),mode:a.escortModeV027||"follow"}});return data};snapshot.__alliesV027=true}
    if(typeof applySave==="function"&&!applySave.__alliesV027){var oldApply=applySave;applySave=function(data){var result=oldApply.apply(this,arguments);setTimeout(function(){var saved=data&&Array.isArray(data.alliesV027)?data.alliesV027:[];saved.forEach(function(row){var a=agentsList().find(function(x){return String(x.id)===String(row.id)});if(!a)return;ensure(a);a.escortActiveV027=!!row.active&&!!a.tradeAllyV026;a.escortHpV027=clamp(n(row.hp,a.escortMaxHpV027),0,n(row.max_hp,a.escortMaxHpV027));a.escortMaxHpV027=Math.max(1,n(row.max_hp,a.escortMaxHpV027));a.escortDownTimerV027=Math.max(0,n(row.down_timer,0));a.escortModeV027=String(row.mode||"follow")});renderHud();updateSettings()},60);return result};applySave.__alliesV027=true}
    installSettings();renderHud()
  }
  window.__egglandsAlliesV027={version:VERSION,maxEscorts:MAX_ESCORTS,install:installHooks,invite:invite,dismiss:dismiss,dismissAll:dismissAll,recall:recall,step:step,active:active,all:allAllies,status:function(){return {version:VERSION,eligible:allAllies().length,active:active().length,attacks:state.attackCount,defeats:state.defeatCount,recalls:state.recallCount,lastMessage:state.lastMessage}}};
  installHooks();setInterval(installHooks,1100);setTimeout(function(){document.title="The Egg Lands v0.27 — Trade Ally Escort";try{if(typeof toast==="function")toast("v0.27 loaded: trusted trade allies can now escort and defend you.")}catch(e){}},1350);
})();
<\/script>
'''
