"""Render the v0.27 authoritative economy and villager-trade browser patch."""
from __future__ import annotations


def render_economy_patch() -> str:
    return r'''
<style id="authoritative-economy-v026-style">
#economyCardV026 .econGridV026{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:7px;margin-top:8px}
#economyCardV026 .econCellV026{border:1px solid var(--line);background:rgba(15,18,24,.58);padding:7px;font-size:9px;line-height:1.45}
#economyCardV026 .econCellV026 strong{display:block;color:var(--gold);font-size:11px;margin-bottom:2px}
#economyCardV026 .econRouteV026{margin-top:8px;border-left:3px solid var(--gold);background:rgba(32,39,53,.62);padding:8px;font-size:9px;line-height:1.5}
#villagerTradeV026{width:min(760px,100%);border:1px solid #6f825b;background:rgba(20,29,24,.96);padding:10px;text-align:left;margin:9px auto 0;font:10px "Courier New",monospace}
#villagerTradeV026 h3{color:#9ed083;font-size:11px;letter-spacing:1px;text-transform:uppercase;margin:0 0 5px}
#villagerTradeV026 .tradeSummaryV026{color:#c8d5bf;line-height:1.5;margin-bottom:7px}
#villagerTradeV026 .tradeColsV026{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:8px}
#villagerTradeV026 .tradeColV026{border:1px solid #445242;padding:7px;background:rgba(10,15,12,.55)}
#villagerTradeV026 .tradeRowV026{display:grid;grid-template-columns:1fr auto auto;gap:6px;align-items:center;border-bottom:1px solid rgba(95,116,88,.35);padding:5px 0}
#villagerTradeV026 .tradeRowV026:last-child{border-bottom:0}
#villagerTradeV026 button{background:#293529;border:1px solid #6f825b;color:#e5efdf;padding:5px 7px;font:9px "Courier New",monospace;cursor:pointer}
#villagerTradeV026 button:disabled{opacity:.42;cursor:not-allowed}
#villagerTradeV026 .tradeAllyV026{color:#e2ad45;font-weight:bold}
#marketAccessBannerV026{border:1px solid var(--line);padding:7px;margin:8px auto;width:min(720px,95%);font-size:9px;line-height:1.45;background:rgba(20,26,35,.85)}
#marketAccessBannerV026.open{border-color:#79c56b;color:#bfe6b6}#marketAccessBannerV026.closed{border-color:#df6c5d;color:#efb0a6}
@media(max-width:650px){#economyCardV026 .econGridV026,#villagerTradeV026 .tradeColsV026{grid-template-columns:1fr}#villagerTradeV026{padding:8px}.tradeRowV026{grid-template-columns:1fr auto!important}}
</style>
<script id="authoritative-economy-v026-script">
(function(){
  "use strict";
  var VERSION="0.27",PROTOCOL=6,EMPIRE_THRESHOLD=3;
  var bridge=window.__egglandsBridgeV024||null;
  var state={sessionId:bridge&&bridge.sessionId?bridge.sessionId:(Date.now().toString(36)+"-econ"),sequence:0,connected:false,mode:"standalone",lastEconomy:null,lastTown:null,lastError:"",syncCount:0,applyCount:0,currentAgent:null,currentProfile:null,lastWorldDay:null};
  var localSessions={};
  var DEMAND={fish:.105,grain:.225,bread:.49,flour:.18,meat:.105,ore:.019,iron_ore:.019,cloth:.009,log:.028,logs:.028,timber:.028,stone:.026,part:.006,parts:.006,hides:.006,tools:.0032};
  var BASE={fish:1,grain:.8,bread:1.3,flour:.9,meat:1.7,ore:1.5,iron_ore:1.5,cloth:2.1,log:.9,logs:.9,timber:.9,stone:1,part:1.8,parts:1.8,hides:1.7,tools:4.8};
  function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d||0)}
  function i(v,d){return Math.round(n(v,d||0))}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function key(v,index,prefix){var s=String(v==null?(prefix+"_"+index):v).trim().toLowerCase().replace(/\s+/g,"_");return s||prefix+"_"+index}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
  function townsList(){try{return typeof towns!=="undefined"&&Array.isArray(towns)?towns:[]}catch(e){return []}}
  function nearest(){try{return typeof nearestTown==="function"?nearestTown():townsList()[0]||null}catch(e){return townsList()[0]||null}}
  function named(values,names,prefix){var out={};if(!Array.isArray(values))return out;values.forEach(function(v,index){out[key(Array.isArray(names)?names[index]:null,index,prefix)]=Math.max(0,n(v,0))});return out}
  function townAgents(town){try{if(town&&Array.isArray(town.agents))return town.agents;if(typeof agents!=="undefined"&&Array.isArray(agents))return agents.filter(function(a){return a&&(!a.town||a.town===town||(a.town&&town&&a.town.name===town.name))})}catch(e){}return []}
  function agentRecord(a){return {id:String(a&&a.id!=null?a.id:"unknown"),name:String(a&&a.name||a&&a.displayName||("Villager "+String(a&&a.id!=null?a.id:""))),activity:String(a&&a.currentActivity||a&&a.job||a&&a.cls||"village work"),wealth:Math.max(0,n(a&&a.wealth,10))}}
  function townObservation(town){
    var goods=typeof GOODS!=="undefined"&&Array.isArray(GOODS)?GOODS:[],materials=typeof MATERIALS!=="undefined"&&Array.isArray(MATERIALS)?MATERIALS:[],population=townAgents(town).length||i(town&&town.population,1),buildings=0;
    if(town&&Array.isArray(town.buildings))buildings=town.buildings.length;else if(town&&town.buildings&&typeof town.buildings==="object")buildings=Object.keys(town.buildings).length;else if(town&&town.building)buildings=1;
    var market=town&&town.market||{},materialPrices=[];if(town&&Array.isArray(town.materialPrices))materialPrices=town.materialPrices;else if(typeof materialPrice==="function")materials.forEach(function(_,idx){try{materialPrices[idx]=materialPrice(town,idx)}catch(e){materialPrices[idx]=0}});
    return {town_name:String(town&&town.name||"unknown"),population:Math.max(1,population),building_count:Math.max(0,buildings),world_day:typeof dayNo!=="undefined"?n(dayNo,0):0,market_inventory:named(market.inventory,goods,"good"),market_prices:named(market.prices,goods,"good"),material_stock:named(town&&town.materialStock,materials,"material"),material_prices:named(materialPrices,materials,"material"),villagers:townAgents(town).slice(0,96).map(agentRecord)}
  }
  function allObservations(){var list=townsList();if(!list.length){var t=nearest();if(t)list=[t]}return list.slice(0,64).map(townObservation)}
  function playerInventory(){var out={};try{var goods=typeof GOODS!=="undefined"&&Array.isArray(GOODS)?GOODS:[],materials=typeof MATERIALS!=="undefined"&&Array.isArray(MATERIALS)?MATERIALS:[];(player.cargo||[]).forEach(function(v,idx){out[key(goods[idx],idx,"good")]=Math.max(0,i(v,0))});(player.materials||[]).forEach(function(v,idx){var k=key(materials[idx],idx,"material");out[k]=(out[k]||0)+Math.max(0,i(v,0))})}catch(e){}return out}
  function post(url,payload){var controller=typeof AbortController!=="undefined"?new AbortController():null,timer=controller?setTimeout(function(){controller.abort()},2300):null;return fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store",signal:controller?controller.signal:undefined}).finally(function(){if(timer)clearTimeout(timer)})}
  function health(){if(!(location.protocol==="http:"||location.protocol==="https:"))return Promise.resolve(false);return fetch("/health",{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("health "+r.status);return r.json()}).then(function(data){state.connected=data.project_version==="0.27"&&!!data.authoritative_town_prices;state.mode=state.connected?"python-authoritative":"standalone";return state.connected}).catch(function(e){state.connected=false;state.mode="standalone";state.lastError=String(e&&e.message||e);return false})}
  function applyMap(array,names,values,prefix){if(!Array.isArray(array)||!values)return;array.forEach(function(_,idx){var k=key(names&&names[idx],idx,prefix);if(Object.prototype.hasOwnProperty.call(values,k))array[idx]=Math.max(0,n(values[k],array[idx]))})}
  function findTown(name){return townsList().find(function(t){return String(t&&t.name)===String(name)})||((nearest()&&String(nearest().name)===String(name))?nearest():null)}
  function applyTownState(townData){var town=findTown(townData.town_name);if(!town)return;town.marketV026Available=!!townData.market_available;town.tradeModeV026=townData.trade_mode;town.controlV026=townData.control;town.economyV026=townData;var goods=typeof GOODS!=="undefined"&&Array.isArray(GOODS)?GOODS:[],materials=typeof MATERIALS!=="undefined"&&Array.isArray(MATERIALS)?MATERIALS:[];if(town.market){applyMap(town.market.inventory,goods,townData.market_inventory,"good");applyMap(town.market.prices,goods,townData.market_prices,"good")}applyMap(town.materialStock,materials,townData.market_inventory,"material");if(Array.isArray(town.materialPrices))applyMap(town.materialPrices,materials,townData.market_prices,"material")}
  function applyEconomy(economy){if(!economy||!economy.towns)return;state.lastEconomy=economy;Object.keys(economy.towns).forEach(function(name){applyTownState(economy.towns[name])});var t=nearest();state.lastTown=t&&economy.towns[String(t.name)]||null;state.applyCount++;try{if(typeof updateUI==="function")updateUI();if(typeof renderMarket==="function")renderMarket();if(typeof renderMarketTable==="function")renderMarketTable()}catch(e){}updateSettings()}
  function localTown(town){
    var obs=townObservation(town),store=town.__localEconomyV026;if(!store){store={town_name:obs.town_name,world_day:obs.world_day,population:obs.population,building_count:obs.building_count,control:town.controlV026||"independent",trade_volume:0,items:{}};var inv=Object.assign({},obs.material_stock,obs.market_inventory),prices=Object.assign({},obs.material_prices,obs.market_prices);Object.keys(Object.assign({},inv,prices)).forEach(function(k){var demand=Math.max(.08,obs.population*(DEMAND[k]||.012));store.items[k]={inventory:inv[k]||demand*7,price:prices[k]||BASE[k]||1.25,base:prices[k]||BASE[k]||1.25,demand:demand,production:0,consumed:0,produced:0}});town.__localEconomyV026=store}
    store.population=obs.population;store.building_count=obs.building_count;store.control=town.controlV026||store.control||"independent";var delta=Math.max(0,obs.world_day-store.world_day);if(delta>0){Object.keys(store.items).forEach(function(k){var item=store.items[k],workers=Math.max(0,Math.round(store.population*.62/Math.max(1,Object.keys(store.items).length))),prod=workers*(k==="grain"?3.6:k==="fish"?1.55:k==="cloth"?.48:1)*(.7+store.building_count*.075)*delta,req=item.demand*delta,available=item.inventory+prod,cons=Math.min(available,req),unmet=Math.max(0,req-available);item.inventory=Math.max(0,available-cons);item.produced=prod;item.consumed=cons;var coverage=item.inventory/Math.max(.05,item.demand),gap=(8-coverage)/8,desired=item.base*clamp(Math.exp(clamp(.78*gap+1.35*(unmet/Math.max(.05,req)),-1.15,1.65)),.32,5.25);item.price+=(desired-item.price)*(1-Math.exp(-.24*delta))});store.world_day=obs.world_day}
    var score=store.population*.58+store.building_count*10.5+Math.min(36,store.trade_volume*.025),market=score>=52&&(store.building_count>=2||store.population>=45),employment=Math.max(1,Math.round(store.population*.62*clamp(.62+store.building_count*.035,.55,.92))),inventory={},prices={},flows={};Object.keys(store.items).forEach(function(k){var item=store.items[k];inventory[k]=item.inventory;prices[k]=item.price;flows[k]={item_id:k,inventory:item.inventory,price:item.price,demand_per_day:item.demand,production_per_day:item.produced/Math.max(.001,delta||1),consumed_last_step:item.consumed,produced_last_step:item.produced,coverage_days:item.inventory/Math.max(.05,item.demand)}});
    return {version:VERSION,town_name:store.town_name,world_day:store.world_day,population:store.population,building_count:store.building_count,control:store.control,development_score:score,market_available:market,trade_mode:market?"town_market":"villagers",working_age_population:Math.round(store.population*.62),employed_population:employment,unemployed_population:Math.max(0,Math.round(store.population*.62)-employment),employment_rate:employment/Math.max(1,Math.round(store.population*.62)),average_daily_wage:1.1+store.building_count*.1,household_wealth:store.population*6,payroll_last_step:employment*(1.1+store.building_count*.1)*delta,consumption_spending_last_step:Object.keys(store.items).reduce(function(a,k){return a+store.items[k].consumed*store.items[k].price},0),treasury:store.population*2.5,trade_volume:store.trade_volume,employment:{producers:employment},market_inventory:inventory,market_prices:prices,item_flows:flows,villager_count:obs.villagers.length,trade_allies:obs.villagers.filter(function(v){var a=townAgents(town).find(function(x){return String(x.id)===String(v.id)});return !!(a&&a.tradeAllyV026)}).length}
  }
  function localEconomy(){var out={version:VERSION,mode:"standalone-demand-economy",authoritative:false,session_id:state.sessionId,sync_count:++state.syncCount,last_sequence:++state.sequence,empire_trade_unlocked:false,empire_territory_count:townsList().filter(function(t){return t.controlV026==="conquered"}).length,empire_market_threshold:EMPIRE_THRESHOLD,towns:{},updated_at_ms:Date.now()};allObservations().forEach(function(obs){var t=findTown(obs.town_name);if(t)out.towns[obs.town_name]=localTown(t)});if(out.empire_territory_count>=EMPIRE_THRESHOLD){out.empire_trade_unlocked=true;Object.keys(out.towns).forEach(function(k){if(out.towns[k].control==="conquered"){out.towns[k].market_available=true;out.towns[k].trade_mode="empire_market"}})}return out}
  async function sync(){
    var payload={session_id:state.sessionId,sequence:++state.sequence,world_day:typeof dayNo!=="undefined"?n(dayNo,0):0,towns:allObservations()};
    if(!state.connected){applyEconomy(localEconomy());return state.lastEconomy}
    try{var response=await post("/api/v1/economy/live/sync",payload);if(!response.ok)throw new Error("economy sync "+response.status);var data=await response.json();state.syncCount++;state.lastError="";applyEconomy(data.economy);return data.economy}catch(e){state.connected=false;state.mode="standalone";state.lastError=String(e&&e.message||e);applyEconomy(localEconomy());return state.lastEconomy}
  }
  function townState(town){var econ=state.lastEconomy&&state.lastEconomy.towns||{};return town&&econ[String(town.name)]||town&&town.economyV026||null}
  function marketAllowed(town){var s=townState(town);return !s||!!s.market_available}
  function installMarketGate(){
    if(typeof openMarket==="function"&&!openMarket.__v026){var oldOpen=openMarket;openMarket=function(town){var target=town||nearest();if(target&&!marketAllowed(target)){if(typeof toast==="function")toast(String(target.name||"This village")+" has no formal market yet. Trade directly with villagers.");return false}return oldOpen.apply(this,arguments)};openMarket.__v026=true}
    if(typeof renderMarket==="function"&&!renderMarket.__v026){var oldRender=renderMarket;renderMarket=function(){var result=oldRender.apply(this,arguments);setTimeout(renderMarketBanner,0);return result};renderMarket.__v026=true}
  }
  function renderMarketBanner(){var table=document.getElementById("marketTable"),parent=table&&table.parentElement;if(!parent)return;var banner=document.getElementById("marketAccessBannerV026");if(!banner){banner=document.createElement("div");banner.id="marketAccessBannerV026";parent.insertBefore(banner,table)}var town=nearest(),s=townState(town);if(!s)return;banner.className=s.market_available?"open":"closed";banner.textContent=s.market_available?(s.trade_mode==="empire_market"?"Empire internal market: conquered territories share stock and converge toward a common price.":"Formal town market: inventories and prices are set by Python production, consumption, and demand."):"No formal market: speak with villagers to see what each household needs and what it can offer."}
  function itemIndex(item){var goods=typeof GOODS!=="undefined"&&Array.isArray(GOODS)?GOODS:[],materials=typeof MATERIALS!=="undefined"&&Array.isArray(MATERIALS)?MATERIALS:[];for(var a=0;a<goods.length;a++)if(key(goods[a],a,"good")===item)return {pool:"cargo",index:a};for(var b=0;b<materials.length;b++)if(key(materials[b],b,"material")===item)return {pool:"materials",index:b};return null}
  function applyPlayerDelta(delta){if(!delta)return false;var gold=n(delta.gold,0);player.coins=Math.max(0,n(player.coins,0)+gold);var items=delta.items||{};Object.keys(items).forEach(function(item){var loc=itemIndex(item);if(!loc)return;var array=loc.pool==="cargo"?player.cargo:player.materials;array[loc.index]=Math.max(0,n(array[loc.index],0)+n(items[item],0))});try{if(typeof updateUI==="function")updateUI();if(typeof saveGame==="function")saveGame(true)}catch(e){}return true}
  function localProfile(agent,town){var s=townState(town)||localTown(town),flows=s.item_flows||{},items=Object.keys(flows).sort(function(a,b){return n(flows[a].coverage_days,0)-n(flows[b].coverage_days,0)}),activity=String(agent&&agent.currentActivity||agent&&agent.job||agent&&agent.cls||"").toLowerCase(),offers=[];if(/fish|shore/.test(activity))offers.push("fish");if(/farm|grain|harvest/.test(activity))offers.push("grain");if(/mine|ore|smith/.test(activity))offers.push("ore");if(/tree|forest|lumber/.test(activity))offers.push(items.includes("logs")?"logs":"log");if(/stone|quarry/.test(activity))offers.push("stone");if(/hunt|game|hide/.test(activity))offers.push(items.includes("parts")?"parts":"part");if(/weav|cloth|tailor/.test(activity))offers.push("cloth");if(!offers.length)offers=items.slice().sort(function(a,b){return n(flows[b].production_per_day,0)-n(flows[a].production_per_day,0)}).slice(0,2);var rel=agent.tradeRelationV026||{trust:0,affinity:0,gratitude:0,lifetime_trade_value:0,trade_count:0};var protect=rel.trust*.42+rel.affinity*.3+rel.gratitude*.18+Math.min(35,rel.lifetime_trade_value*.12),discount=clamp((rel.trust+rel.affinity)/400,0,.18);var wants=items.slice(0,3).map(function(k){return {item_id:k,quantity:Math.max(1,Math.round(n(flows[k].demand_per_day,1)*.35)),price:n(s.market_prices[k],BASE[k]||1)*1.1}}),offerRows=offers.filter(function(k){return s.market_prices[k]!=null}).slice(0,3).map(function(k){var stock=agent.tradeStockV026&&agent.tradeStockV026[k];if(stock==null)stock=1+Math.floor(Math.abs(Math.sin(n(agent.id,1)*17+k.length))*4);agent.tradeStockV026=agent.tradeStockV026||{};agent.tradeStockV026[k]=stock;return {item_id:k,quantity:stock,price:n(s.market_prices[k],BASE[k]||1)*(1.18-discount)}});return {villager_id:String(agent.id),name:String(agent.name||agent.displayName||("Villager "+agent.id)),activity:String(agent.currentActivity||"village work"),trust:rel.trust,affinity:rel.affinity,gratitude:rel.gratitude,lifetime_trade_value:rel.lifetime_trade_value,trade_count:rel.trade_count,protection_score:protect,willing_to_defend:protect>=35&&rel.trade_count>=3,wants:wants,offers:offerRows,demand_summary:wants.map(function(x){return x.item_id}).join(", "),relationship_label:protect>=35?"trade ally":rel.trade_count?"regular customer":"new contact",market_available:s.market_available,trade_mode:s.trade_mode}
  }
  async function getProfile(agent){var town=agent&&agent.town&&agent.town.name?agent.town:nearest();if(!town)return null;state.currentAgent=agent;var local=localProfile(agent,town);if(!state.connected){state.currentProfile=local;renderTrade(local);return local}try{var r=await post("/api/v1/economy/live/villager",{session_id:state.sessionId,town_name:String(town.name),villager:agentRecord(agent)});if(!r.ok)throw new Error("villager "+r.status);var data=await r.json();state.currentProfile=data.villager||local;renderTrade(state.currentProfile);return state.currentProfile}catch(e){state.lastError=String(e&&e.message||e);state.currentProfile=local;renderTrade(local);return local}}
  function tradeRows(title,rows,side){return '<div class="tradeColV026"><strong>'+esc(title)+'</strong>'+(rows&&rows.length?rows.map(function(row){return '<div class="tradeRowV026"><span>'+esc(row.item_id)+' × '+esc(row.quantity)+'</span><span>'+n(row.price,0).toFixed(2)+'c</span><button type="button" data-side="'+side+'" data-item="'+esc(row.item_id)+'">'+(side==="buy"?'Buy 1':'Sell 1')+'</button></div>'}).join(""):'<div class="sub">Nothing available right now.</div>')+'</div>'}
  function renderTrade(profile){var dialogue=document.getElementById("dialogue");if(!dialogue||!profile)return;var panel=document.getElementById("villagerTradeV026");if(!panel){panel=document.createElement("div");panel.id="villagerTradeV026";dialogue.appendChild(panel)}var ally=profile.willing_to_defend?'<span class="tradeAllyV026">This trade ally is willing to defend you and the route.</span>':'Protection score '+n(profile.protection_score,0).toFixed(1)+' / 35';panel.innerHTML='<h3>Direct Trade — '+esc(profile.name)+'</h3><div class="tradeSummaryV026">Current demand: '+esc(profile.demand_summary||"nothing urgent")+'. Relationship: '+esc(profile.relationship_label||"new contact")+'. '+ally+'</div><div class="tradeColsV026">'+tradeRows("They are selling",profile.offers,"buy")+tradeRows("They want to buy",profile.wants,"sell")+'</div><div id="tradeMessageV026" class="sub" style="margin-top:7px"></div>';panel.querySelectorAll("button[data-side]").forEach(function(button){button.addEventListener("click",function(){performTrade(button.dataset.side,button.dataset.item)})})}
  async function performTrade(side,item){var agent=state.currentAgent,town=agent&&agent.town&&agent.town.name?agent.town:nearest(),message=document.getElementById("tradeMessageV026");if(!agent||!town)return;var profile=state.currentProfile||localProfile(agent,town),rows=side==="buy"?profile.offers:profile.wants,row=rows.find(function(x){return x.item_id===item});if(!row)return;buttonBusy(true);try{var result;if(state.connected){var r=await post("/api/v1/economy/live/trade",{session_id:state.sessionId,town_name:String(town.name),villager:agentRecord(agent),side:side,item_id:item,quantity:1,player_gold:n(player.coins,0),player_inventory:playerInventory()});var data=await r.json();if(!r.ok||data.status!=="accepted")throw new Error(data.message||"Trade rejected");result=data;applyPlayerDelta(result.player_delta);applyTownState(result.town);state.currentProfile=result.villager}else{var cost=n(row.price,0),loc=itemIndex(item);if(!loc)throw new Error("That item is not carried by the current inventory system");var array=loc.pool==="cargo"?player.cargo:player.materials;if(side==="buy"){if(n(player.coins,0)<cost)throw new Error("You cannot afford that trade");if(n(row.quantity,0)<1)throw new Error("They have sold out");player.coins-=cost;array[loc.index]=n(array[loc.index],0)+1;agent.tradeStockV026[item]=Math.max(0,n(agent.tradeStockV026[item],0)-1)}else{if(n(array[loc.index],0)<1)throw new Error("You do not have that item");array[loc.index]-=1;player.coins+=cost}var rel=agent.tradeRelationV026||{trust:0,affinity:0,gratitude:0,lifetime_trade_value:0,trade_count:0};rel.trade_count++;rel.lifetime_trade_value+=cost;rel.trust+=2.4;rel.affinity+=1.2;rel.gratitude+=side==="sell"?2.3:1.1;agent.tradeRelationV026=rel;state.currentProfile=localProfile(agent,town);agent.tradeAllyV026=state.currentProfile.willing_to_defend;try{if(typeof updateUI==="function")updateUI();if(typeof saveGame==="function")saveGame(true)}catch(e){}}
      updateAgentRelation(agent,state.currentProfile);renderTrade(state.currentProfile);if(message)message.textContent="Trade completed: "+side+" 1 "+item+" for "+n(row.price,0).toFixed(2)+" coins.";sync()
    }catch(e){if(message)message.textContent=String(e&&e.message||e)}finally{buttonBusy(false)}}
  function buttonBusy(value){var panel=document.getElementById("villagerTradeV026");if(panel)panel.querySelectorAll("button").forEach(function(b){b.disabled=!!value})}
  function updateAgentRelation(agent,profile){if(!agent||!profile)return;agent.tradeRelationV026={trust:n(profile.trust,0),affinity:n(profile.affinity,0),gratitude:n(profile.gratitude,0),lifetime_trade_value:n(profile.lifetime_trade_value,0),trade_count:i(profile.trade_count,0)};agent.tradeAllyV026=!!profile.willing_to_defend;if(agent.mindV30&&agent.mindV30.opinions&&agent.mindV30.opinions.player){var o=agent.mindV30.opinions.player;o.trust=Math.max(n(o.trust,0),n(profile.trust,0));o.gratitude=Math.max(n(o.gratitude,0),n(profile.gratitude,0));o.affection=Math.max(n(o.affection,0),n(profile.affinity,0)*.7)}if(agent.tradeAllyV026)agent.currentActivity="protecting a profitable friendship and trade route"}
  function installDialogueTrade(){if(typeof openDialogue==="function"&&!openDialogue.__v026){var old=openDialogue;openDialogue=function(agent){var result=old.apply(this,arguments);setTimeout(function(){getProfile(agent)},0);return result};openDialogue.__v026=true}}
  function drawStalls(){if(typeof ctx==="undefined"||typeof camera==="undefined"||typeof scene!=="undefined"&&scene!=="world")return;townsList().forEach(function(town){var s=townState(town);if(!s||!s.market_available)return;var p=town.marketPoint||town.market&&town.market.point||{x:town.x||0,y:town.y||0},x=n(p.x,0)-n(camera.x,0),y=n(p.y,0)-n(camera.y,0);if(x<-30||y<-30||x>900||y>600)return;ctx.save();ctx.fillStyle="rgba(8,10,13,.35)";ctx.fillRect(x-12,y+9,28,4);ctx.fillStyle="#6f4b2e";ctx.fillRect(x-11,y-4,24,15);ctx.fillStyle="#e2ad45";ctx.fillRect(x-14,y-10,30,6);ctx.fillStyle="#9c4e3e";for(var q=-12;q<15;q+=8)ctx.fillRect(x+q,y-10,4,6);ctx.fillStyle="#eadfc7";ctx.font="6px monospace";ctx.textAlign="center";ctx.fillText(s.trade_mode==="empire_market"?"EMPIRE MARKET":"MARKET",x+1,y-14);ctx.restore()})}
  function installStallDraw(){if(typeof drawCombatEffects==="function"&&!drawCombatEffects.__econV026){var old=drawCombatEffects;drawCombatEffects=function(){var result=old.apply(this,arguments);drawStalls();return result};drawCombatEffects.__econV026=true}}
  function setControl(control){var town=nearest();if(!town)return Promise.resolve(false);if(state.connected)return post("/api/v1/economy/live/control",{session_id:state.sessionId,town_name:String(town.name),control:control}).then(function(r){return r.json().then(function(data){if(!r.ok)throw new Error(data.message||"Control change rejected");applyEconomy(data.economy);return true})}).catch(function(e){state.lastError=String(e&&e.message||e);updateSettings();return false});town.controlV026=control;var count=townsList().filter(function(t){return t.controlV026==="conquered"}).length;if(count>=EMPIRE_THRESHOLD)townsList().forEach(function(t){if(t.controlV026==="conquered"){t.marketV026Available=true;t.tradeModeV026="empire_market"}});sync();return Promise.resolve(true)}
  function settingsHtml(s,econ){var empire=econ||{},town=nearest(),t=townState(town),connected=state.connected?"Python authoritative":"Standalone demand economy",route=t?(t.trade_mode==="villagers"?"Direct villager trade":t.trade_mode==="empire_market"?"Empire internal market":"Formal town market"):"Waiting for town state";return '<h3>Living Economy <span class="hdArchitectureBadgeV34">v0.27</span></h3><div class="sub">Python owns town inventory, prices, production, employment, wages, and consumption when connected. Prices rise from unmet demand and fall when stock coverage is high.</div><div class="econRouteV026"><strong>'+esc(connected)+' · '+esc(route)+'</strong><br>'+(t?esc(t.town_name)+' · population '+i(t.population,0)+' · development '+n(t.development_score,0).toFixed(1)+' · '+(t.market_available?'market open':'no formal market'):'No town observation yet')+'</div><div class="econGridV026">'+(t?'<div class="econCellV026"><strong>'+Math.round(n(t.employment_rate,0)*100)+'% employed</strong>'+i(t.employed_population,0)+' workers · '+i(t.unemployed_population,0)+' unemployed</div><div class="econCellV026"><strong>'+n(t.average_daily_wage,0).toFixed(2)+' coin wage</strong>'+n(t.payroll_last_step,0).toFixed(1)+' payroll · '+n(t.consumption_spending_last_step,0).toFixed(1)+' consumption</div><div class="econCellV026"><strong>'+i(t.trade_allies,0)+' trade allies</strong>Villagers cross the protection threshold through repeated mutually useful trade.</div><div class="econCellV026"><strong>'+(empire.empire_trade_unlocked?'Empire market unlocked':i(empire.empire_territory_count,0)+' / '+EMPIRE_THRESHOLD+' territories')+'</strong>Conquered towns pool stock after the threshold.</div>':'')+'</div><div class="row" style="margin-top:9px;justify-content:flex-start"><button class="uibtn" id="syncEconomyV026" type="button">Sync economy now</button><button class="uibtn godOnly" id="independentV026" type="button">Dev: Independent</button><button class="uibtn godOnly" id="friendlyV026" type="button">Dev: Friendly</button><button class="uibtn godOnly" id="conqueredV026" type="button">Dev: Conquered</button></div><div id="economyErrorV026" class="sub" style="margin-top:6px">'+esc(state.lastError||"")+'</div>'}
  function installSettings(){var wrap=document.getElementById("settingsContent");if(!wrap)return false;var oldToggle=document.getElementById("authorityToggleV024");if(oldToggle){var box=oldToggle.closest("div[style]");if(box)box.style.display="none"}var card=document.getElementById("economyCardV026");if(!card){card=document.createElement("div");card.id="economyCardV026";card.className="menuCard";wrap.appendChild(card)}card.innerHTML=settingsHtml(state,state.lastEconomy);var syncButton=card.querySelector("#syncEconomyV026");if(syncButton)syncButton.addEventListener("click",sync);[["independentV026","independent"],["friendlyV026","friendly"],["conqueredV026","conquered"]].forEach(function(pair){var b=card.querySelector("#"+pair[0]);if(b){if(typeof godMode!=="undefined"&&godMode)b.classList.add("enabled");b.addEventListener("click",function(){setControl(pair[1])})}});return true}
  function updateSettings(){var card=document.getElementById("economyCardV026");if(card)installSettings();renderMarketBanner()}
  function installSave(){if(typeof snapshot==="function"&&!snapshot.__econV026){var oldSnap=snapshot;snapshot=function(){var data=oldSnap.apply(this,arguments);data.version=Math.max(26,n(data.version,0));data.economyV026={towns:townsList().map(function(t){return {name:t.name,control:t.controlV026||"independent",local:t.__localEconomyV026||null,agents:townAgents(t).filter(function(a){return a.tradeRelationV026}).map(function(a){return {id:a.id,relation:a.tradeRelationV026,stock:a.tradeStockV026||{},ally:!!a.tradeAllyV026}})}})};return data};snapshot.__econV026=true}if(typeof applySave==="function"&&!applySave.__econV026){var oldApply=applySave;applySave=function(data){var result=oldApply.apply(this,arguments);setTimeout(function(){var saved=data&&data.economyV026&&data.economyV026.towns||[];saved.forEach(function(st){var t=findTown(st.name);if(!t)return;t.controlV026=st.control||"independent";t.__localEconomyV026=st.local||null;(st.agents||[]).forEach(function(sa){var a=townAgents(t).find(function(x){return String(x.id)===String(sa.id)});if(a){a.tradeRelationV026=sa.relation;a.tradeStockV026=sa.stock;a.tradeAllyV026=!!sa.ally}})});sync()},0);return result};applySave.__econV026=true}}
  function install(){installMarketGate();installDialogueTrade();installStallDraw();installSave();installSettings()}
  if(typeof renderSettings==="function"&&!renderSettings.__econV026){var oldSettings=renderSettings;renderSettings=function(){var result=oldSettings.apply(this,arguments);setTimeout(installSettings,0);return result};renderSettings.__econV026=true}
  window.__egglandsEconomyV026={version:VERSION,protocolVersion:PROTOCOL,state:function(){return Object.assign({},state)},sync:sync,apply:applyEconomy,townState:townState,marketAllowed:marketAllowed,profile:getProfile,trade:performTrade,setControl:setControl,install:install,localEconomy:localEconomy};
  install();health().then(function(){sync()});setInterval(function(){install();var day=typeof dayNo!=="undefined"?n(dayNo,0):0;if(state.connected||state.lastWorldDay!==day){state.lastWorldDay=day;sync()}else updateSettings()},2200);setTimeout(function(){document.title="The Egg Lands v0.27 — Living Economy";if(typeof toast==="function")toast("v0.27 loaded: demand now drives town prices, inventory, jobs, wages, and villager trade.")},1200);
})();
<\/script>
'''
